apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-service
  template:
    metadata:
      labels:
        app: dummy-service
    spec:
      containers:
      - name: dummy-service
        image: localhost:5000/dummy-service:latest # Replace with your image
        ports:
        - containerPort: 50051

---
apiVersion: v1
kind: Service
metadata:
  name: dummy-service
  labels:
    app: dummy-service
spec:
  ports:
  - port: 50051
    name: grpc
  selector:
    app: dummy-service